# Generated by Django 5.2.4 on 2025-08-07 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="image",
            field=models.ImageField(default=1, upload_to="news_images"),
            preserve_default=False,
        ),
    ]
