# Generated by Django 5.2.5 on 2025-08-22 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blogdata", "0002_tag_blog_tags"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blog",
            name="tags",
        ),
    ]
