# Generated by Django 5.2.5 on 2025-08-22 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogdata", "0003_remove_blog_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="tags",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="blogdata.tag",
            ),
        ),
    ]
