# Generated by Django 5.2.5 on 2025-08-22 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogdata", "0004_blog_tags"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blog",
            name="tags",
        ),
        migrations.AddField(
            model_name="blog",
            name="tags",
            field=models.ManyToManyField(blank=True, null=True, to="blogdata.tag"),
        ),
    ]
