# Generated by Django 5.2.5 on 2025-08-29 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogdata", "0005_remove_blog_tags_blog_tags"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone_number", models.BigIntegerField()),
                ("message", models.TextField()),
            ],
        ),
    ]
